security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    users:
      entity:
        class: App\News\Domain\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/admin/api/login
      stateless: true
      json_login:
        check_path: /admin/api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    admin_api:
      pattern: ^/admin/api
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api, roles: PUBLIC_ACCESS }
    - { path: ^/admin/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin/api, roles: IS_AUTHENTICATED_FULLY }
