version: '3.8'

services:
  # PHP-FPM
  app:
    build:
      context: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - var:/var/www/html/var
    depends_on:
      - db
    networks:
      - symfony

  # Nginx
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  # MySQL
  db:
    image: mysql:5.7
    container_name: symfony_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data:
  var:
