api_login_check:
    path: /admin/api/login_check

client_routes:
    resource: '../config/routes/client.yaml'

admin_routes:
    resource: '../config/routes/admin.yaml'
    prefix: /admin

admin_home:
    path: /admin/{reactRouting}
    controller: App\News\Interface\Http\Admin\Controller\AdminController::index
    defaults:
        reactRouting: ''
    requirements:
        reactRouting: ".*"

client_home:
    path: /{reactRouting}
    controller: App\News\Interface\Http\Client\Controller\ClientController::index
    defaults:
        reactRouting: ''
    requirements:
        reactRouting: ".*"