# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/images/articles'
    app.recipient_email: 'recipient@example.com'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/News/Domain/Entity/'
            - '../src/Identity/Domain/Entity/'
            - '../src/Mudimind/Domain/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    command_handlers:
        namespace: App\News\Application\Command\Handler\
        resource: '%kernel.project_dir%/src/News/Application/Command/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    identity_command_handlers:
        namespace: App\Identity\Application\Command\Handler\
        resource: '%kernel.project_dir%/src/Identity/Application/Command/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    App\News\Application\Command\Handler\CreateImageHandler:
        arguments:
            $imagesDirectory: '%images_directory%'
            $slugger: '@slugger'
            $imageRepository: '@App\News\Domain\Repository\ImageRepositoryInterface'
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    query_handlers:
        namespace: App\News\Application\Query\Handler\
        resource: '%kernel.project_dir%/src/News/Application/Query/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    mudimind_command_handlers:
        namespace: App\Mudimind\Application\Command\Handler\
        resource: '%kernel.project_dir%/src/Mudimind/Application/Command/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    mudimind_query_handlers:
        namespace: App\Mudimind\Application\Query\Handler\
        resource: '%kernel.project_dir%/src/Mudimind/Application/Query/Handler/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: messenger.bus.default }

    App\News\Infrastructure\Repository\ArticleRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\News\Domain\Repository\ArticleRepositoryInterface:
        alias: App\News\Infrastructure\Repository\ArticleRepository

    App\News\Infrastructure\Repository\CategoryRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\News\Domain\Repository\CategoryRepositoryInterface:
        alias: App\News\Infrastructure\Repository\CategoryRepository

    App\News\Infrastructure\Repository\CommentRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\News\Domain\Repository\CommentRepositoryInterface:
        alias: App\News\Infrastructure\Repository\CommentRepository

    App\News\Infrastructure\Repository\ImageRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\News\Domain\Repository\ImageRepositoryInterface:
        alias: App\News\Infrastructure\Repository\ImageRepository

    App\Identity\Infrastructure\Repository\UserRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\Identity\Domain\Repository\UserRepositoryInterface:
        alias: App\Identity\Infrastructure\Repository\UserRepository

    App\News\Application\Query\Finder\ArticleFinderInterface:
        alias: App\News\Infrastructure\Query\ArticleFinder

    App\News\Application\Query\Finder\CategoryFinderInterface:
        alias: App\News\Infrastructure\Query\CategoryFinder

    App\News\Application\Query\Finder\CommentFinderInterface:
        alias: App\News\Infrastructure\Query\CommentFinder

    App\Mudimind\Infrastructure\Repository\MasseurRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\Mudimind\Domain\Repository\MasseurRepositoryInterface:
        alias: App\Mudimind\Infrastructure\Repository\MasseurRepository

    App\Mudimind\Infrastructure\Repository\ClientRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\Mudimind\Domain\Repository\ClientRepositoryInterface:
        alias: App\Mudimind\Infrastructure\Repository\ClientRepository

    App\Mudimind\Infrastructure\Repository\BookRepository:
        tags:
            - { name: 'doctrine.repository_service' }

    App\Mudimind\Domain\Repository\BookRepositoryInterface:
        alias: App\Mudimind\Infrastructure\Repository\BookRepository

    App\Mudimind\Application\Query\Finder\FreeSpotFinderInterface:
        alias: App\Mudimind\Infrastructure\Query\FreeSpotFinder

    App\News\Interface\Cli\SendTopWeeklyArticlesCommand:
        arguments:
            $recipientEmail: '%env(RECIPIENT_EMAIL)%'
        tags:
            - { name: 'console.command' }

    App\Shared\Infrastructure\Serializer\CollectionIdNormalizer:
        tags: [ 'serializer.normalizer' ]

    App\News\Infrastructure\Serializer\ArticleDTONormalizer: ~

    App\News\Infrastructure\Serializer\CategoryWithTopArticlesDTONormalizer: ~


    App\Shared\Infrastructure\Http\Request\BaseRequestValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 200 }
