App\News\Domain\Comment:
  type: entity
  table: comment
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    author:
      type: string
      length: 255
    content:
      type: text
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
    deletedAt:
      type: datetime
      column: deleted_at
      nullable: true
