App\News\Domain\Image:
  type: entity
  table: image
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      length: 255
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
    deletedAt:
      type: datetime
      column: deleted_at
      nullable: true
